In [1]:
import requests
import numpy as np
import scipy as sp
import pandas as pd
import datetime
import json

In [3]:
#获取数据,并保存到iris.txt中
r = requests.get("http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data")
with open('iris.txt','w') as f:
    f.write(r.text)

In [4]:
#打开文本文件，读取iris.txt数据

with open('iris.txt','r') as f:
    lines = f.readlines()
    
for line in lines:
    print line

5.1,3.5,1.4,0.2,Iris-setosa

4.9,3.0,1.4,0.2,Iris-setosa

4.7,3.2,1.3,0.2,Iris-setosa

4.6,3.1,1.5,0.2,Iris-setosa

5.0,3.6,1.4,0.2,Iris-setosa

5.4,3.9,1.7,0.4,Iris-setosa

4.6,3.4,1.4,0.3,Iris-setosa

5.0,3.4,1.5,0.2,Iris-setosa

4.4,2.9,1.4,0.2,Iris-setosa

4.9,3.1,1.5,0.1,Iris-setosa

5.4,3.7,1.5,0.2,Iris-setosa

4.8,3.4,1.6,0.2,Iris-setosa

4.8,3.0,1.4,0.1,Iris-setosa

4.3,3.0,1.1,0.1,Iris-setosa

5.8,4.0,1.2,0.2,Iris-setosa

5.7,4.4,1.5,0.4,Iris-setosa

5.4,3.9,1.3,0.4,Iris-setosa

5.1,3.5,1.4,0.3,Iris-setosa

5.7,3.8,1.7,0.3,Iris-setosa

5.1,3.8,1.5,0.3,Iris-setosa

5.4,3.4,1.7,0.2,Iris-setosa

5.1,3.7,1.5,0.4,Iris-setosa

4.6,3.6,1.0,0.2,Iris-setosa

5.1,3.3,1.7,0.5,Iris-setosa

4.8,3.4,1.9,0.2,Iris-setosa

5.0,3.0,1.6,0.2,Iris-setosa

5.0,3.4,1.6,0.4,Iris-setosa

5.2,3.5,1.5,0.2,Iris-setosa

5.2,3.4,1.4,0.2,Iris-setosa

4.7,3.2,1.6,0.2,Iris-setosa

4.8,3.1,1.6,0.2,Iris-setosa

5.4,3.4,1.5,0.4,Iris-setosa

5.2,4.1,1.5,0.1,Iris-setosa

5.5,4.2,1.4,0.2,Iris-setosa

4.9,3.1,1.5,0.1,Iris-setosa

5.0,3.2,1.2,0.2,Iris-setosa

5.5,3.5,1.3,0.2,Iris-setosa

4.9,3.1,1.5,0.1,Iris-setosa

4.4,3.0,1.3,0.2,Iris-setosa

5.1,3.4,1.5,0.2,Iris-setosa

5.0,3.5,1.3,0.3,Iris-setosa

4.5,2.3,1.3,0.3,Iris-setosa

4.4,3.2,1.3,0.2,Iris-setosa

5.0,3.5,1.6,0.6,Iris-setosa

5.1,3.8,1.9,0.4,Iris-setosa

4.8,3.0,1.4,0.3,Iris-setosa

5.1,3.8,1.6,0.2,Iris-setosa

4.6,3.2,1.4,0.2,Iris-setosa

5.3,3.7,1.5,0.2,Iris-setosa

5.0,3.3,1.4,0.2,Iris-setosa

7.0,3.2,4.7,1.4,Iris-versicolor

6.4,3.2,4.5,1.5,Iris-versicolor

6.9,3.1,4.9,1.5,Iris-versicolor

5.5,2.3,4.0,1.3,Iris-versicolor

6.5,2.8,4.6,1.5,Iris-versicolor

5.7,2.8,4.5,1.3,Iris-versicolor

6.3,3.3,4.7,1.6,Iris-versicolor

4.9,2.4,3.3,1.0,Iris-versicolor

6.6,2.9,4.6,1.3,Iris-versicolor

5.2,2.7,3.9,1.4,Iris-versicolor

5.0,2.0,3.5,1.0,Iris-versicolor

5.9,3.0,4.2,1.5,Iris-versicolor

6.0,2.2,4.0,1.0,Iris-versicolor

6.1,2.9,4.7,1.4,Iris-versicolor

5.6,2.9,3.6,1.3,Iris-versicolor

6.7,3.1,4.4,1.4,Iris-versicolor

5.6,3.0,4.5,1.5,Iris-versicolor

5.8,2.7,4.1,1.0,Iris-versicolor

6.2,2.2,4.5,1.5,Iris-versicolor

5.6,2.5,3.9,1.1,Iris-versicolor

5.9,3.2,4.8,1.8,Iris-versicolor

6.1,2.8,4.0,1.3,Iris-versicolor

6.3,2.5,4.9,1.5,Iris-versicolor

6.1,2.8,4.7,1.2,Iris-versicolor

6.4,2.9,4.3,1.3,Iris-versicolor

6.6,3.0,4.4,1.4,Iris-versicolor

6.8,2.8,4.8,1.4,Iris-versicolor

6.7,3.0,5.0,1.7,Iris-versicolor

6.0,2.9,4.5,1.5,Iris-versicolor

5.7,2.6,3.5,1.0,Iris-versicolor

5.5,2.4,3.8,1.1,Iris-versicolor

5.5,2.4,3.7,1.0,Iris-versicolor

5.8,2.7,3.9,1.2,Iris-versicolor

6.0,2.7,5.1,1.6,Iris-versicolor

5.4,3.0,4.5,1.5,Iris-versicolor

6.0,3.4,4.5,1.6,Iris-versicolor

6.7,3.1,4.7,1.5,Iris-versicolor

6.3,2.3,4.4,1.3,Iris-versicolor

5.6,3.0,4.1,1.3,Iris-versicolor

5.5,2.5,4.0,1.3,Iris-versicolor

5.5,2.6,4.4,1.2,Iris-versicolor

6.1,3.0,4.6,1.4,Iris-versicolor

5.8,2.6,4.0,1.2,Iris-versicolor

5.0,2.3,3.3,1.0,Iris-versicolor

5.6,2.7,4.2,1.3,Iris-versicolor

5.7,3.0,4.2,1.2,Iris-versicolor

5.7,2.9,4.2,1.3,Iris-versicolor

6.2,2.9,4.3,1.3,Iris-versicolor

5.1,2.5,3.0,1.1,Iris-versicolor

5.7,2.8,4.1,1.3,Iris-versicolor

6.3,3.3,6.0,2.5,Iris-virginica

5.8,2.7,5.1,1.9,Iris-virginica

7.1,3.0,5.9,2.1,Iris-virginica

6.3,2.9,5.6,1.8,Iris-virginica

6.5,3.0,5.8,2.2,Iris-virginica

7.6,3.0,6.6,2.1,Iris-virginica

4.9,2.5,4.5,1.7,Iris-virginica

7.3,2.9,6.3,1.8,Iris-virginica

6.7,2.5,5.8,1.8,Iris-virginica

7.2,3.6,6.1,2.5,Iris-virginica

6.5,3.2,5.1,2.0,Iris-virginica

6.4,2.7,5.3,1.9,Iris-virginica

6.8,3.0,5.5,2.1,Iris-virginica

5.7,2.5,5.0,2.0,Iris-virginica

5.8,2.8,5.1,2.4,Iris-virginica

6.4,3.2,5.3,2.3,Iris-virginica

6.5,3.0,5.5,1.8,Iris-virginica

7.7,3.8,6.7,2.2,Iris-virginica

7.7,2.6,6.9,2.3,Iris-virginica

6.0,2.2,5.0,1.5,Iris-virginica

6.9,3.2,5.7,2.3,Iris-virginica

5.6,2.8,4.9,2.0,Iris-virginica

7.7,2.8,6.7,2.0,Iris-virginica

6.3,2.7,4.9,1.8,Iris-virginica

6.7,3.3,5.7,2.1,Iris-virginica

7.2,3.2,6.0,1.8,Iris-virginica

6.2,2.8,4.8,1.8,Iris-virginica

6.1,3.0,4.9,1.8,Iris-virginica

6.4,2.8,5.6,2.1,Iris-virginica

7.2,3.0,5.8,1.6,Iris-virginica

7.4,2.8,6.1,1.9,Iris-virginica

7.9,3.8,6.4,2.0,Iris-virginica

6.4,2.8,5.6,2.2,Iris-virginica

6.3,2.8,5.1,1.5,Iris-virginica

6.1,2.6,5.6,1.4,Iris-virginica

7.7,3.0,6.1,2.3,Iris-virginica

6.3,3.4,5.6,2.4,Iris-virginica

6.4,3.1,5.5,1.8,Iris-virginica

6.0,3.0,4.8,1.8,Iris-virginica

6.9,3.1,5.4,2.1,Iris-virginica

6.7,3.1,5.6,2.4,Iris-virginica

6.9,3.1,5.1,2.3,Iris-virginica

5.8,2.7,5.1,1.9,Iris-virginica

6.8,3.2,5.9,2.3,Iris-virginica

6.7,3.3,5.7,2.5,Iris-virginica

6.7,3.0,5.2,2.3,Iris-virginica

6.3,2.5,5.0,1.9,Iris-virginica

6.5,3.0,5.2,2.0,Iris-virginica

6.2,3.4,5.4,2.3,Iris-virginica

5.9,3.0,5.1,1.8,Iris-virginica

In [5]:
#使用pandas读取txt数据，使用读取CSV的读取方法，方便后面快速识别结构化数据
irisdata = pd.read_csv('iris.txt',header = None)
irisdata

      0    1    2    3                4
0   5.1  3.5  1.4  0.2      Iris-setosa
1   4.9  3.0  1.4  0.2      Iris-setosa
2   4.7  3.2  1.3  0.2      Iris-setosa
3   4.6  3.1  1.5  0.2      Iris-setosa
4   5.0  3.6  1.4  0.2      Iris-setosa
5   5.4  3.9  1.7  0.4      Iris-setosa
6   4.6  3.4  1.4  0.3      Iris-setosa
7   5.0  3.4  1.5  0.2      Iris-setosa
8   4.4  2.9  1.4  0.2      Iris-setosa
9   4.9  3.1  1.5  0.1      Iris-setosa
10  5.4  3.7  1.5  0.2      Iris-setosa
11  4.8  3.4  1.6  0.2      Iris-setosa
12  4.8  3.0  1.4  0.1      Iris-setosa
13  4.3  3.0  1.1  0.1      Iris-setosa
14  5.8  4.0  1.2  0.2      Iris-setosa
15  5.7  4.4  1.5  0.4      Iris-setosa
16  5.4  3.9  1.3  0.4      Iris-setosa
17  5.1  3.5  1.4  0.3      Iris-setosa
18  5.7  3.8  1.7  0.3      Iris-setosa
19  5.1  3.8  1.5  0.3      Iris-setosa
20  5.4  3.4  1.7  0.2      Iris-setosa
21  5.1  3.7  1.5  0.4      Iris-setosa
22  4.6  3.6  1.0  0.2      Iris-setosa
23  5.1  3.3  1.7  0.5      Iris-setosa
24  4.8  3.4  1.9  0.2      Iris-setosa
25  5.0  3.0  1.6  0.2      Iris-setosa
26  5.0  3.4  1.6  0.4      Iris-setosa
27  5.2  3.5  1.5  0.2      Iris-setosa
28  5.2  3.4  1.4  0.2      Iris-setosa
29  4.7  3.2  1.6  0.2      Iris-setosa
30  4.8  3.1  1.6  0.2      Iris-setosa
31  5.4  3.4  1.5  0.4      Iris-setosa
32  5.2  4.1  1.5  0.1      Iris-setosa
33  5.5  4.2  1.4  0.2      Iris-setosa
34  4.9  3.1  1.5  0.1      Iris-setosa
35  5.0  3.2  1.2  0.2      Iris-setosa
36  5.5  3.5  1.3  0.2      Iris-setosa
37  4.9  3.1  1.5  0.1      Iris-setosa
38  4.4  3.0  1.3  0.2      Iris-setosa
39  5.1  3.4  1.5  0.2      Iris-setosa
40  5.0  3.5  1.3  0.3      Iris-setosa
41  4.5  2.3  1.3  0.3      Iris-setosa
42  4.4  3.2  1.3  0.2      Iris-setosa
43  5.0  3.5  1.6  0.6      Iris-setosa
44  5.1  3.8  1.9  0.4      Iris-setosa
45  4.8  3.0  1.4  0.3      Iris-setosa
46  5.1  3.8  1.6  0.2      Iris-setosa
47  4.6  3.2  1.4  0.2      Iris-setosa
48  5.3  3.7  1.5  0.2      Iris-setosa
49  5.0  3.3  1.4  0.2      Iris-setosa
50  7.0  3.2  4.7  1.4  Iris-versicolor
51  6.4  3.2  4.5  1.5  Iris-versicolor
52  6.9  3.1  4.9  1.5  Iris-versicolor
53  5.5  2.3  4.0  1.3  Iris-versicolor
54  6.5  2.8  4.6  1.5  Iris-versicolor
55  5.7  2.8  4.5  1.3  Iris-versicolor
56  6.3  3.3  4.7  1.6  Iris-versicolor
57  4.9  2.4  3.3  1.0  Iris-versicolor
58  6.6  2.9  4.6  1.3  Iris-versicolor
59  5.2  2.7  3.9  1.4  Iris-versicolor
    ...  ...  ...  ...              ...

[151 rows x 5 columns]

In [6]:
#上面已经将txt中的数据按照结构化的行列形式展现出来了
#那么如何给每一列取个名字呢
colnames = ['sepal_length','sepal_width','petal_length','petal_width','class']
irisdata.columns = colnames
irisdata

    sepal_length  sepal_width  petal_length  petal_width            class
0            5.1          3.5           1.4          0.2      Iris-setosa
1            4.9          3.0           1.4          0.2      Iris-setosa
2            4.7          3.2           1.3          0.2      Iris-setosa
3            4.6          3.1           1.5          0.2      Iris-setosa
4            5.0          3.6           1.4          0.2      Iris-setosa
5            5.4          3.9           1.7          0.4      Iris-setosa
6            4.6          3.4           1.4          0.3      Iris-setosa
7            5.0          3.4           1.5          0.2      Iris-setosa
8            4.4          2.9           1.4          0.2      Iris-setosa
9            4.9          3.1           1.5          0.1      Iris-setosa
10           5.4          3.7           1.5          0.2      Iris-setosa
11           4.8          3.4           1.6          0.2      Iris-setosa
12           4.8          3.0           1.4          0.1      Iris-setosa
13           4.3          3.0           1.1          0.1      Iris-setosa
14           5.8          4.0           1.2          0.2      Iris-setosa
15           5.7          4.4           1.5          0.4      Iris-setosa
16           5.4          3.9           1.3          0.4      Iris-setosa
17           5.1          3.5           1.4          0.3      Iris-setosa
18           5.7          3.8           1.7          0.3      Iris-setosa
19           5.1          3.8           1.5          0.3      Iris-setosa
20           5.4          3.4           1.7          0.2      Iris-setosa
21           5.1          3.7           1.5          0.4      Iris-setosa
22           4.6          3.6           1.0          0.2      Iris-setosa
23           5.1          3.3           1.7          0.5      Iris-setosa
24           4.8          3.4           1.9          0.2      Iris-setosa
25           5.0          3.0           1.6          0.2      Iris-setosa
26           5.0          3.4           1.6          0.4      Iris-setosa
27           5.2          3.5           1.5          0.2      Iris-setosa
28           5.2          3.4           1.4          0.2      Iris-setosa
29           4.7          3.2           1.6          0.2      Iris-setosa
30           4.8          3.1           1.6          0.2      Iris-setosa
31           5.4          3.4           1.5          0.4      Iris-setosa
32           5.2          4.1           1.5          0.1      Iris-setosa
33           5.5          4.2           1.4          0.2      Iris-setosa
34           4.9          3.1           1.5          0.1      Iris-setosa
35           5.0          3.2           1.2          0.2      Iris-setosa
36           5.5          3.5           1.3          0.2      Iris-setosa
37           4.9          3.1           1.5          0.1      Iris-setosa
38           4.4          3.0           1.3          0.2      Iris-setosa
39           5.1          3.4           1.5          0.2      Iris-setosa
40           5.0          3.5           1.3          0.3      Iris-setosa
41           4.5          2.3           1.3          0.3      Iris-setosa
42           4.4          3.2           1.3          0.2      Iris-setosa
43           5.0          3.5           1.6          0.6      Iris-setosa
44           5.1          3.8           1.9          0.4      Iris-setosa
45           4.8          3.0           1.4          0.3      Iris-setosa
46           5.1          3.8           1.6          0.2      Iris-setosa
47           4.6          3.2           1.4          0.2      Iris-setosa
48           5.3          3.7           1.5          0.2      Iris-setosa
49           5.0          3.3           1.4          0.2      Iris-setosa
50           7.0          3.2           4.7          1.4  Iris-versicolor
51           6.4          3.2           4.5          1.5  Iris-versicolor
52           6.9          3.1           4.9          1.5  Iris-versicolor
53           5.5          2.3           4.0          1.3  Iris-versicolor
54           6.5          2.8           4.6          1.5  Iris-versicolor
55           5.7          2.8           4.5          1.3  Iris-versicolor
56           6.3          3.3           4.7          1.6  Iris-versicolor
57           4.9          2.4           3.3          1.0  Iris-versicolor
58           6.6          2.9           4.6          1.3  Iris-versicolor
59           5.2          2.7           3.9          1.4  Iris-versicolor
             ...          ...           ...          ...              ...

[151 rows x 5 columns]

In [9]:
#如何对数据进行过滤呢，比如说我们需要找到那些width为最大值的数据
irisdata[irisdata['petal_width']==irisdata['petal_width'].max()]

     sepal_length  sepal_width  petal_length  petal_width           class
100           6.3          3.3           6.0          2.5  Iris-virginica
109           7.2          3.6           6.1          2.5  Iris-virginica
144           6.7          3.3           5.7          2.5  Iris-virginica

[3 rows x 5 columns]

In [10]:
#如何对数据进行切片呢,：：30的意思是从0开始到结束，每隔30个数取一个数
#：2的意思是前两列数据进行显示
irisdata.iloc[::30,:2]

     sepal_length  sepal_width
0             5.1          3.5
30            4.8          3.1
60            5.0          2.0
90            5.5          2.6
120           6.9          3.2
150           NaN          NaN

[6 rows x 2 columns]

In [14]:
#数据集中的列表class有三类，那么如何获取每一类到底有多少个呢？
#以及如何获取一些基本的统计数据，如最大最小值，中位数，平均数等
#下面的{0:>5}表示间距
print irisdata['class'].value_counts()
for x in xrange(4):
    s = irisdata.iloc[:,x] #取每一列
    print '{0:<12}'.format(s.name.upper()),"Statistics",'{0:>5} {1:>5} {2:>5} {3:>5}'.format(s.max(),s.min(),round(s.mean(),2),round(s.std(),2))

Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
dtype: int64
SEPAL_LENGTH Statistics   7.9   4.3  5.84  0.83
SEPAL_WIDTH  Statistics   4.4   2.0  3.05  0.43
PETAL_LENGTH Statistics   6.9   1.0  3.76  1.76
PETAL_WIDTH  Statistics   2.5   0.1   1.2  0.76

In [16]:
#如何做快速mapreduce,如何分组
slogs = lambda x:sp.log(x)*x
entpy = lambda x:sp.exp((slogs(x.sum())-x.map(slogs).sum())/x.sum())
irisdata.groupby('class').agg(entpy)

                 sepal_length  sepal_width  petal_length  petal_width
class
Iris-setosa         49.878745    49.695242     49.654909    45.810069
Iris-versicolor     49.815081    49.680665     49.694505    49.452305
Iris-virginica      49.772059    49.714500     49.761700    49.545918

[3 rows x 4 columns]

In [17]:
#下面是DataFrame，Series,index,numpy的使用
seris = pd.Series(np.random.random(4))
print seris,type(seris)
print seris.index
print seris.values

0    0.398761
1    0.392206
2    0.197414
3    0.993730
dtype: float64 <class 'pandas.core.series.Series'>
Int64Index([0, 1, 2, 3], dtype='int64')
[ 0.39876061  0.39220556  0.19741422  0.99372989]

In [18]:
#Series支持过滤的原理同numpy
print seris>0
print seris[seris>0]

0    True
1    True
2    True
3    True
dtype: bool
0    0.398761
1    0.392206
2    0.197414
3    0.993730
dtype: float64

In [19]:
#同样也支持Broadcasting的使用
print seris*2
print seris+5

0    0.797521
1    0.784411
2    0.394828
3    1.987460
dtype: float64
0    5.398761
1    5.392206
2    5.197414
3    5.993730
dtype: float64

In [20]:
#还支持函数的使用
print np.exp(seris)
f_np = np.frompyfunc(lambda x:np.exp(x*2+5),1,1)
print f_np(seris)

0    1.489977
1    1.480242
2    1.218249
3    2.701291
dtype: float64
0    329.4818
1    325.1905
2    220.2644
3    1082.967
dtype: object

In [22]:
#在随机数产生的同时添加列名，也就是索引
seris2 = pd.Series(seris.values,index = ['norm_'+unicode(i) for i in xrange(4)])
print seris2,type(seris2)
print seris2.index
print type(seris2.index)
print seris2.values

norm_0    0.398761
norm_1    0.392206
norm_2    0.197414
norm_3    0.993730
dtype: float64 <class 'pandas.core.series.Series'>
Index([u'norm_0', u'norm_1', u'norm_2', u'norm_3'], dtype='object')
<class 'pandas.core.index.Index'>
[ 0.39876061  0.39220556  0.19741422  0.99372989]

In [23]:
#通过索引访问其中的数
print seris2[['norm_0','norm_3']]

norm_0    0.398761
norm_3    0.993730
dtype: float64

In [24]:
print 'norm_0' in seris2
print 'norm_6' in seris2

True
False

In [25]:
#series也可以操作字典
Series3_Dict = {"Japan":"Tokyo","S.Korea":"Seoul","China":"Beijing"}
Series3_pdSeries = pd.Series(Series3_Dict)
print Series3_pdSeries
print Series3_pdSeries.values
print Series3_pdSeries.index

China      Beijing
Japan        Tokyo
S.Korea      Seoul
dtype: object
['Beijing' 'Tokyo' 'Seoul']
Index([u'China', u'Japan', u'S.Korea'], dtype='object')

In [26]:
#也可以按照自己需求进行列排列
Series4_IndexList = ["Japan","China","Singapore","S.Korea"]
Series4_pdSeries = pd.Series( Series3_Dict ,index = Series4_IndexList)
print Series4_pdSeries
print Series4_pdSeries.values
print Series4_pdSeries.index
print Series4_pdSeries.isnull()
print Series4_pdSeries.notnull()

Japan          Tokyo
China        Beijing
Singapore        NaN
S.Korea        Seoul
dtype: object
['Tokyo' 'Beijing' nan 'Seoul']
Index([u'Japan', u'China', u'Singapore', u'S.Korea'], dtype='object')
Japan        False
China        False
Singapore     True
S.Korea      False
dtype: bool
Japan         True
China         True
Singapore    False
S.Korea       True
dtype: bool

In [27]:
#可以给数据序列和index本身起个名字，这样就可以方便进行后面关联分析
Series4_pdSeries.name = "Capital Series"
Series4_pdSeries.index.name = "Nation"
print Series4_pdSeries

Nation
Japan          Tokyo
China        Beijing
Singapore        NaN
S.Korea        Seoul
Name: Capital Series, dtype: object

In [29]:
#index的名字也可以重复
Series5_IndexList = ['A','B','B','C']
Series5 = pd.Series(seris2.values,index = Series5_IndexList)
print Series5
print Series5[['B','A']]

A    0.398761
B    0.392206
B    0.197414
C    0.993730
dtype: float64
B    0.392206
B    0.197414
A    0.398761
dtype: float64

In [31]:
#DataFrame数据框的使用
#输入二维数组的值，然后使用DataFrame将其归并为数组形式，并且起个列名
dataNumPy = np.asarray([('Japan','Tokyo',4000),('S.Korea','Seoul',1300),('China','Beijing',9100)])
DF1 = pd.DataFrame(dataNumPy,columns=['nation','capital','GDP'])
DF1

    nation  capital   GDP
0    Japan    Tokyo  4000
1  S.Korea    Seoul  1300
2    China  Beijing  9100

[3 rows x 3 columns]

In [32]:
#如何将字典数据保存到数据框中
dataDict = {'nation':['Japan','S.Korea','China'],'capital':['Tokyo','Seoul','Beijing'],'GDP':[
4900,1300,9100]}
DF2 = pd.DataFrame(dataDict)
DF2

    GDP  capital   nation
0  4900    Tokyo    Japan
1  1300    Seoul  S.Korea
2  9100  Beijing    China

[3 rows x 3 columns]

In [33]:
#如何改变列的位置
DF21 = pd.DataFrame(DF2,columns=['nation','capital','GDP'])
DF21

    nation  capital   GDP
0    Japan    Tokyo  4900
1  S.Korea    Seoul  1300
2    China  Beijing  9100

[3 rows x 3 columns]

In [34]:
#改变行的编号
DF22 = pd.DataFrame(DF2,columns=['nation','capital','GDP'],index = [2,0,1])
DF22

    nation  capital   GDP
2    China  Beijing  9100
0    Japan    Tokyo  4900
1  S.Korea    Seoul  1300

[3 rows x 3 columns]

In [35]:
#如何取出列
print DF22.nation,DF22.capital
print DF22['GDP']

2      China
0      Japan
1    S.Korea
Name: nation, dtype: object 2    Beijing
0      Tokyo
1      Seoul
Name: capital, dtype: object
2    9100
0    4900
1    1300
Name: GDP, dtype: int64

In [36]:
#从数据框中取出至少两列
print DF22[0:1] #给出的实际是DataFrame
print DF22.ix[0] #通过对应Index给出⾏行

  nation  capital   GDP
2  China  Beijing  9100

[1 rows x 3 columns]
nation     Japan
capital    Tokyo
GDP         4900
Name: 0, dtype: object

In [37]:
#如何利用切片取出指定行，列
print DF22.iloc[0,:]
print DF22.iloc[:,0]

nation       China
capital    Beijing
GDP           9100
Name: 2, dtype: object
2      China
0      Japan
1    S.Korea
Name: nation, dtype: object

In [38]:
#如何动态的增加列
DF22['population'] = [1600,130,55]
DF22

    nation  capital   GDP  population
2    China  Beijing  9100        1600
0    Japan    Tokyo  4900         130
1  S.Korea    Seoul  1300          55

[3 rows x 4 columns]

In [39]:
#datetime库的使用
dates = [datetime.datetime(2015,1,1),datetime.datetime(2015,1,8),datetime.datetime(2015,1,30)]
pd.DatetimeIndex(dates)

<class 'pandas.tseries.index.DatetimeIndex'>
[2015-01-01 00:00:00, ..., 2015-01-30 00:00:00]
Length: 3, Freq: None, Timezone: None

In [40]:
dates

[datetime.datetime(2015, 1, 1, 0, 0),
 datetime.datetime(2015, 1, 8, 0, 0),
 datetime.datetime(2015, 1, 30, 0, 0)]

In [41]:
periodindex1 = pd.period_range('2015-01','2015-04',freq='M')
print periodindex1

PeriodIndex([u'2015-01', u'2015-02', u'2015-03', u'2015-04'], freq='M')